#!/usr/bin/env bash
set -Eeuo pipefail

[[ "${EUID}" -eq 0 ]] || { echo "Run as root: sudo bash uninstall.sh" >&2; exit 77; }

keep_state=0
while (($#)); do
  case "$1" in
    --keep-state) keep_state=1 ;;
    -h|--help)
      cat <<'USAGE'
Usage: sudo bash uninstall.sh [--keep-state]

Removes Bridge-owned local services, containers, CLI files and generated config.
Cloudflare DNS records, the remote tunnel, Docker, cloudflared packages and the
operator's Cloudflare account credentials are intentionally preserved.
USAGE
      exit 0
      ;;
    *) echo "Unknown option: $1" >&2; exit 64 ;;
  esac
  shift
done

log() { printf '[Bridge] %s\n' "$*"; }
warn() { printf '[Bridge] WARNING: %s\n' "$*" >&2; }
die() { printf '[Bridge] ERROR: %s\n' "$*" >&2; exit 1; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "${script_dir}/../.." && pwd)"
config_file="${BRIDGE_CONFIG_FILE:-/etc/intqwq-bridge/config}"

# The config is root-owned and generated by Bridge itself using shell-escaped
# scalar values. It is the authoritative source for non-default install paths.
if [[ -r "${config_file}" ]]; then
  # shellcheck disable=SC1090
  source "${config_file}"
fi

bridge_root="${BRIDGE_ROOT:-${project_root}}"
state_dir="${BRIDGE_STATE_DIR:-/var/lib/intqwq-bridge}"
operator_user="${BRIDGE_OPERATOR_USER:-${SUDO_USER:-root}}"
cli_path="${BRIDGE_CLI_PATH:-/usr/local/sbin/bridge}"

[[ "${bridge_root}" == /* && "${bridge_root}" != "/" ]] || die "Refusing unsafe BRIDGE_ROOT: ${bridge_root}"
[[ "${state_dir}" == /* && "${state_dir}" != "/" ]] || die "Refusing unsafe BRIDGE_STATE_DIR: ${state_dir}"
[[ "${config_file}" == /* ]] || die "BRIDGE_CONFIG_FILE must be absolute."
[[ "${cli_path}" == /* ]] || die "BRIDGE_CLI_PATH must be absolute."

log "Stopping Bridge services..."
if command -v systemctl >/dev/null 2>&1; then
  systemctl disable --now bridge-cloudflared.service >/dev/null 2>&1 || true
  systemctl disable --now bridge-edge.service >/dev/null 2>&1 || true
fi

# Stop the compose project explicitly as a fallback if the systemd unit is
# missing, damaged or was never installed.
if command -v docker >/dev/null 2>&1 && [[ -f "${bridge_root}/compose.yml" && -f "${bridge_root}/.env" ]]; then
  if ! docker compose --project-directory "${bridge_root}" --env-file "${bridge_root}/.env" down --remove-orphans; then
    warn "Docker Compose cleanup failed; continuing with the remaining local cleanup."
  fi
fi

rm -f /etc/systemd/system/bridge-cloudflared.service
rm -f /etc/systemd/system/bridge-edge.service
if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
  systemctl reset-failed bridge-cloudflared.service bridge-edge.service >/dev/null 2>&1 || true
fi

# bridge.yml is Bridge-owned. Keep cert.pem and tunnel credential JSON files so
# a later reinstall can reuse the existing remote tunnel safely.
operator_home=""
if command -v getent >/dev/null 2>&1; then
  operator_home="$(getent passwd "${operator_user}" 2>/dev/null | cut -d: -f6 || true)"
fi
if [[ -n "${operator_home}" && "${operator_home}" == /* ]]; then
  rm -f "${operator_home}/.cloudflared/bridge.yml"
fi

rm -f -- "${cli_path}"
rm -f -- "${config_file}"
rmdir "$(dirname "${config_file}")" >/dev/null 2>&1 || true
rm -f -- "${bridge_root}/.env"

if [[ "${keep_state}" == "1" ]]; then
  log "Preserved Bridge state: ${state_dir}"
else
  rm -rf -- "${state_dir}"
  log "Removed Bridge state: ${state_dir}"
fi

log "Bridge local services and CLI are removed."
log "Preserved Docker/cloudflared packages, Cloudflare account credentials, remote tunnel and DNS records."
log "If this host will never use the tunnel again, remove the remote tunnel/DNS explicitly from Cloudflare after verifying no other host depends on them."
