#!/usr/bin/env bash
set -Eeuo pipefail

[[ "${EUID}" -eq 0 ]] || { echo "Run as root: sudo bash uninstall.sh" >&2; exit 77; }

keep_state=0
purge_env=0

usage() {
  cat <<'USAGE'
Usage: sudo bash uninstall.sh [--keep-state] [--purge-env]

Remove Bridge-owned local services, containers, CLI files, generated config and,
by default, Bridge runtime state.

Preserved intentionally:
  - Docker and cloudflared packages
  - Cloudflare account credentials (cert.pem)
  - Cloudflare tunnel credential JSON files
  - the remote Cloudflare tunnel
  - all Cloudflare DNS records
  - the repository checkout and .env unless --purge-env is supplied

Options:
  --keep-state  Preserve the Bridge registry and generated route state.
  --purge-env   Remove the repository .env file as well.
USAGE
}

while (( $# > 0 )); do
  case "$1" in
    --keep-state) keep_state=1; shift ;;
    --purge-env) purge_env=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 64 ;;
  esac
done

log() { printf '[Bridge uninstall] %s\n' "$*"; }
warn() { printf '[Bridge uninstall] WARNING: %s\n' "$*" >&2; }
die() { printf '[Bridge uninstall] ERROR: %s\n' "$*" >&2; exit 1; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_root="$(cd "${script_dir}/../.." && pwd)"
config_file="${BRIDGE_CONFIG_FILE:-/etc/intqwq-bridge/config}"

# The config is root-owned and generated by Bridge using shell-escaped scalar
# values. Use it when present so custom state/CLI paths are removed correctly.
if [[ -r "${config_file}" ]]; then
  # shellcheck disable=SC1090
  source "${config_file}"
fi

bridge_root="${BRIDGE_ROOT:-${project_root}}"
state_dir="${BRIDGE_STATE_DIR:-/var/lib/intqwq-bridge}"
operator_user="${BRIDGE_OPERATOR_USER:-${SUDO_USER:-root}}"
cli_path="${BRIDGE_CLI_PATH:-/usr/local/sbin/bridge}"

[[ "${bridge_root}" == /* && "${bridge_root}" != "/" ]] || die "Refusing unsafe BRIDGE_ROOT: ${bridge_root}"
[[ "${state_dir}" == /* && "${state_dir}" != "/" ]] || die "Refusing unsafe BRIDGE_STATE_DIR: ${state_dir}"
[[ "${config_file}" == /* && "${config_file}" != "/" ]] || die "Refusing unsafe BRIDGE_CONFIG_FILE: ${config_file}"
[[ "${cli_path}" == /* && "${cli_path}" != "/" ]] || die "Refusing unsafe BRIDGE_CLI_PATH: ${cli_path}"

registry_dir="${state_dir}/registry"
if [[ -d "${registry_dir}" ]]; then
  registered_count="$(find "${registry_dir}" -maxdepth 1 -type f -name '*.json' -print 2>/dev/null | wc -l | tr -d ' ')"
  if [[ "${registered_count}" != "0" ]]; then
    warn "${registered_count} registered service(s) will lose public ingress when Bridge stops. Application services themselves are not removed."
  fi
fi

log "Stopping Bridge services"
if command -v systemctl >/dev/null 2>&1; then
  systemctl disable --now bridge-cloudflared.service >/dev/null 2>&1 || true
  systemctl disable --now bridge-edge.service >/dev/null 2>&1 || true
fi

# Compose cleanup is a fallback when the systemd unit is absent or damaged.
if command -v docker >/dev/null 2>&1 && [[ -f "${bridge_root}/compose.yml" ]]; then
  compose_args=(docker compose --project-directory "${bridge_root}")
  [[ ! -f "${bridge_root}/.env" ]] || compose_args+=(--env-file "${bridge_root}/.env")
  if ! "${compose_args[@]}" down --remove-orphans; then
    warn "Docker Compose cleanup failed; continuing with remaining local cleanup."
  fi
fi

log "Removing Bridge service definitions"
rm -f -- /etc/systemd/system/bridge-cloudflared.service /etc/systemd/system/bridge-edge.service
if command -v systemctl >/dev/null 2>&1; then
  systemctl daemon-reload || true
  systemctl reset-failed bridge-cloudflared.service bridge-edge.service >/dev/null 2>&1 || true
fi

# bridge.yml is generated by Bridge. Keep cert.pem and tunnel credential JSON
# files because they may be shared with other cloudflared workflows and allow a
# later Bridge reinstall to reuse the existing remote tunnel safely.
operator_home=""
if command -v getent >/dev/null 2>&1; then
  operator_home="$(getent passwd "${operator_user}" 2>/dev/null | cut -d: -f6 || true)"
fi
if [[ -n "${operator_home}" && "${operator_home}" == /* && "${operator_home}" != "/" ]]; then
  rm -f -- "${operator_home}/.cloudflared/bridge.yml"
fi

log "Removing Bridge CLI and local configuration"
rm -f -- "${cli_path}"
rm -f -- "${config_file}"
config_dir="$(dirname "${config_file}")"
[[ "${config_dir}" == "/" ]] || rmdir "${config_dir}" >/dev/null 2>&1 || true

if [[ "${keep_state}" == "1" ]]; then
  log "Preserved Bridge state: ${state_dir}"
else
  rm -rf -- "${state_dir}"
  log "Removed Bridge state: ${state_dir}"
fi

if [[ "${purge_env}" == "1" ]]; then
  rm -f -- "${bridge_root}/.env"
  log "Removed ${bridge_root}/.env"
else
  log "Preserved ${bridge_root}/.env"
fi

cat <<'DONE'
[Bridge uninstall] Complete.
[Bridge uninstall] Docker/cloudflared packages, Cloudflare credentials, the remote tunnel and DNS records were preserved.
[Bridge uninstall] Remove remote Cloudflare resources only after verifying that no other host or application depends on them.
DONE
